### ISSUE TITLE
Recipe Support

### ISSUE THREAD

**Issue by thxmike** [bjrmatos/jsreport-pug#116]
Will this only work with the phantom-pdf or html recipes? I was trying to get it to work with the xlsx recipe but I have not had much luck

**Comment by bjrmatos** [comment]
hi! it should work with any recipe that expects html as input (phantom-pdf, electron-pdf, etc), it should work with the `xlsx` recipe, do you have an example to try?

**Comment by thxmike** [comment]
So I tried to convert the following that is written for handlebars

```
{{#xlsxAdd "xl/worksheets/sheet1.xml" "worksheet.sheetData[0].row"}}
    <row>
        <c t="inlineStr"><is><t>Hello world</t></is></c>
        <c><v>11</v></c>
    </row>
{{/xlsxAdd}}

{{{xlsxPrint}}}
```

This can be seen here
https://playground.jsreport.net/studio/workspace/r1vaurbw/3
It is the Add Row Template. 

I have tried something like this
https://playground.jsreport.net/studio/workspace/By3LiJgex/4

and variations of the above but I could not get it. 

Not sure what I am missing

**Comment by pofider** [comment]
I'm afraid this won't work. The internal jsreport-xlsx implementation is compatible only with handlebars and jsrender at this moment. This is because we need some advanced features like access to the root context and block helpers and this is not the same across all engines.
