### ISSUE TITLE
Installation Guide - Instalación con jsreport-cli

### ISSUE THREAD

**Issue by joeesteves** [bjrmatos/jsreport-pug#129]
@bjrmatos Como estas ? 
Gracias por el engine!
Me costo un poco encontrar la vuelta para hacer una instalación asique una vez que logre hacerlo hice un mini guía que puede servir a otros .
Te lo pongo acá por si querés incluir en el readme

To install Jade / Pug (or any other template engine) with jsreport you con follow these steps:
1. First off all, create a local folder that will hold the server, i.e.  (~/myTools/jsreport)
2. Go to that directory. (cd ~/myTools/jsreport)
3. yarn global add jsreport-cli (you can also use npm install -g jsreport-cli)
4. Execute the command:  jsreport init (this will create folder structure)
5. Add jade or ejs or the template engine package to folder with these command: yarn add  jsreport-jade
start the server running jsreport start  

[Guide Link](https://ceibo.co/category/javascript/)

saludos

**Comment by bjrmatos** [comment]
@ponyesteves hola! todo bien 😃 gracias por la guía, de hecho que hace las cosas mas claras el tener los pasos exactos para instalar la extension.
 
si gustas tambien puedes enviar un pull request directo al README de este repo, con gusto le hago merge 👍 , de lo contrario yo mismo agregare esto al README una ves que me desocupe un poco

**Comment by bjrmatos** [comment]
solved via #130
