### ISSUE TITLE
templateHelpers not working in pug engine

### ISSUE THREAD

**Issue by rajusubramaniam** [bjrmatos/jsreport-pug#131]
> I have this code in NodeJS.

```
jsreport.render({
   template: {
		content: 'h1 Hello #{templateHelpers.foo()}',
		helpers: { foo: () => { return 'world' } },
		engine: 'pug',
		recipe: 'chrome-pdf'
	},
	data: {
					},
}).then((out) => {
	out.stream.pipe(res);
}).catch((e) => {
	res.end(e.message);
});
```

I tried various combinations and could not get visibility of the helper method 'foo'. Am I missing something?

`Error while executing templating engine. templateHelpers.foo is not a function on line 1`

**Comment by pofider** [comment]
Please don't create duplicated issues. Thank you.

https://github.com/jsreport/jsreport/issues/627
