### ISSUE TITLE
Does not work with jsreport

### ISSUE THREAD

**Issue by jleach** [bjrmatos/jsreport-pug#49]
I don't think this works with jsreport, at least not with jsreport-core. If you follow the example on the jsreport-core website you can't really drop this in place as an engine. You just get the {"name": ... "main":...} object back. Can't really initialize it like other modules and tell jsreport to .use() it.

**Comment by bjrmatos** [comment]
you're right, this extension only work with main `jsreport`, in fact this extension was created before `jsreport-core` was a thing, i will publish a new version supporting `jsreportCore.use()`

**Comment by bjrmatos** [comment]
it should work now! in v1.2.0 thnks
